# Generated by Django 3.0 on 2020-06-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='speech',
        ),
        migrations.AddField(
            model_name='speech',
            name='translations',
            field=models.ManyToManyField(related_name='speeches', to='dictionary.Translation'),
        ),
        migrations.AlterField(
            model_name='speech',
            name='meanings',
            field=models.ManyToManyField(related_name='speeches', to='dictionary.Meaning'),
        ),
    ]
