# Generated by Django 3.0 on 2020-07-02 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_auto_20200623_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_occurrence', models.IntegerField(default=0)),
                ('word', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='dictionary.Word')),
            ],
        ),
    ]
