# Generated by Django 3.0.8 on 2020-07-29 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.CharField(max_length=255)),
                ('translation', models.CharField(max_length=255)),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='program.VocabularyProgram')),
            ],
        ),
        migrations.DeleteModel(
            name='VocabularyUnderstanding',
        ),
    ]
