# Generated by Django 3.0 on 2020-07-30 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20200720_2248'),
        ('program', '0002_auto_20200729_2156'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_programs', to='member.Member')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VocabularyUnderstanding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_understandings', to='member.Member')),
            ],
        ),
        migrations.RenameField(
            model_name='programenrollment',
            old_name='enrolled_date',
            new_name='enrolled_at',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='program',
        ),
        migrations.RemoveField(
            model_name='vocabularyprogram',
            name='count',
        ),
        migrations.RemoveField(
            model_name='vocabularyprogram',
            name='enrollments',
        ),
        migrations.RemoveField(
            model_name='vocabularyprogram',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='vocabularyprogram',
            name='words',
        ),
        migrations.AddField(
            model_name='programenrollment',
            name='vocabulary_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_programs', to='program.VocabularyProgram'),
        ),
        migrations.DeleteModel(
            name='SubVocabularyProgram',
        ),
        migrations.AddField(
            model_name='vocabularyunderstanding',
            name='vocabulary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='understandings', to='program.Vocabulary'),
        ),
        migrations.AddField(
            model_name='vocabularylist',
            name='program',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_list', to='program.VocabularyProgram'),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='vocabulary_program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_programs', to='program.VocabularyProgram'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='flash_card',
            field=models.ManyToManyField(related_name='vocabularies', to='program.FlashCard'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='vocabulary_list',
            field=models.ManyToManyField(related_name='vocabularies', to='program.VocabularyList'),
        ),
    ]
