# Generated by Django 3.0 on 2020-08-03 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_auto_20200730_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='flash_card',
            field=models.ManyToManyField(blank=True, related_name='vocabularies', to='program.FlashCard'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='vocabulary_list',
            field=models.ManyToManyField(blank=True, related_name='vocabularies', to='program.VocabularyList'),
        ),
    ]
