# Generated by Django 3.0 on 2020-08-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0004_auto_20200803_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='translation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
