# Generated by Django 3.0 on 2020-08-03 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0005_auto_20200803_2339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='vocabulary_list',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='vocabulary_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='program.VocabularyList'),
            preserve_default=False,
        ),
    ]
