# Generated by Django 3.0 on 2020-10-12 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_wordanalysis'),
        ('member', '0002_auto_20200720_2248'),
        ('program', '0006_auto_20200803_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('alias', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='programenrollment',
            name='vocabulary_program',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='flash_card',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='rep',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='translation',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='vocabulary_list',
        ),
        migrations.AddField(
            model_name='programenrollment',
            name='vocab_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='program.VocabularyProgram'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='vocab_program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='program_vocabularies', to='program.VocabularyProgram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='program_vocabularies', to='dictionary.Word'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='member.Member'),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='vocabulary_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='program.VocabularyProgram'),
        ),
        migrations.DeleteModel(
            name='VocabularyList',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='bank',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='program_vocabularies', to='program.VocabularyBank'),
            preserve_default=False,
        ),
    ]
