# Generated by Django 3.0 on 2020-10-14 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0007_auto_20201012_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='vocab_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='program_vocabularies', to='program.VocabularyProgram'),
        ),
    ]
