# Generated by Django 3.0 on 2020-10-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_wordanalysis'),
        ('member', '0002_auto_20200720_2248'),
        ('program', '0008_auto_20201014_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabulary',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='program.VocabularyBank'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='vocab_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocabularies', to='program.VocabularyProgram'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='dictionary.Word'),
        ),
        migrations.AlterField(
            model_name='vocabularyunderstanding',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='understandings', to='member.Member'),
        ),
    ]
