# Generated by Django 3.0 on 2020-10-17 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0009_auto_20201015_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programenrollment',
            old_name='vocab_program',
            new_name='vocabulary_program',
        ),
    ]
