# Generated by Django 3.0 on 2020-10-17 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0010_auto_20201017_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramProgress',
            fields=[
                ('learned', models.IntegerField(default=0)),
                ('reviewing', models.IntegerField(default=0)),
                ('new', models.IntegerField(default=0)),
                ('enrollment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='program.ProgramEnrollment')),
            ],
        ),
    ]
