# Generated by Django 3.0 on 2020-10-17 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0011_programprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='created_at',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='vocabularies',
            field=models.ManyToManyField(related_name='flashcards', to='program.Vocabulary'),
        ),
    ]
