# Generated by Django 3.0 on 2020-10-17 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0012_auto_20201017_1235'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProgramProgress',
        ),
    ]
