# Generated by Django 3.0 on 2020-10-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0014_flashcard_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='progress',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=4),
        ),
    ]
