# Generated by Django 3.0 on 2020-11-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0016_vocabularyunderstanding_mastered_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularyTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rep', models.CharField(max_length=1500)),
                ('speech', models.CharField(blank=True, max_length=50, null=True)),
                ('vocabulary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='program.Vocabulary')),
            ],
        ),
    ]
