# Generated by Django 3.0 on 2020-11-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0017_vocabularytranslation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vocabulary',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='vocabulary',
            name='word',
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='rep',
            field=models.CharField(default='tenp', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='vocab_program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vocabularies', to='program.VocabularyProgram'),
        ),
        migrations.DeleteModel(
            name='VocabularyBank',
        ),
    ]
